version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # don't update Quarkus as we want the extension to depend on the latest Quarkus LTS version
      - dependency-name: io.quarkus:*

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
